= Multiple Consumers in a Fan-Out Configuration
Mario Gray <mgray@pivotal.io>
:Author Initials: MVG
:toc:
:icons:
:numbered:
:imagesdir: ./graphics
:website: https://docs.spring.io/spring/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html
:note: Drain the [BAYEUX]

== This Demo
This demo will stand up Spring application service that exposes a reactive WebSocket service through the Spring 5's WebSockets API.
It will demonstrate multicasting events to web sockets.  We will keep this simple, and direct.  Most of the work that I am trying to convey deals with Reactive concepts.

== Problem documentation
Stock ticker will produce values containting it's ticker symbol, and a price.  Provided a client subscribes to a ticker 'symbol' that will ensure any web socket pulls emit just the subscribed entities.
This way, we can have a 1:many (fan out) situation in which each ticker is it's own Supplier.

== WebSocket Server
This server will attempt to react to each tick with a response to each subscriber.  Each client will consume a Flux<Stock>, in which subscription entities are pushed to. 
For this to work with websockets, we will create the consumer for each client sink, such that {onEvent -> push to client stream}.

== The Client
yes, a client!

= Afterwords
Next stop, Security!

== References/Readling List

* Spring WebFlux guide
** https://docs.spring.io/spring/docs/5.0.0.BUILD-SNAPSHOT/spring-framework-reference/html/web-reactive.html
** https://docs.spring.io/spring/docs/current/spring-framework-reference/web-reactive.html

* Articles
** https://ordina-jworks.github.io/reactive/2016/12/12/Reactive-Programming-Spring-Reactor.html

* W3C Proposals
** https://tools.ietf.org/html/rfc6455

* Theory
** http://reactivex.io/documentation/operators.html
** https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/debounce.md


